<a href="https://colab.research.google.com/github/Kyash24/Python_Concepts_In_Action/blob/main/04_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy array
# Revision Point: NumPy (Numerical Python) is a fundamental package for numerical computation in Python.
# It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

In [ ]:
# list - You can store diff data types elements

# Disadvantages (compared to NumPy arrays):
# It takes a lot of time to execute (less efficient for numerical operations)
# It consumes large memory (stores actual objects, not just values)
# We cannot perform arithmetic operations directly on entire lists (element-wise operations require loops)
# Revision Point: Python lists are heterogeneous and dynamic, good for general-purpose data collection, but less efficient for numerical tasks.

In [ ]:
#[1,2,3,4,5,6]
# List actually stores the pointer to the memorylocation where the a ctual element is

In [ ]:
# Numpy introduces us numpy array
# Key Advantages of NumPy arrays:
# 1. Memory Efficiency: Stores elements in contiguous memory blocks, reducing memory overhead.
# 2. Speed: Optimized C implementations for numerical operations, making them much faster than Python lists for large datasets.
# 3. Functionality: Provides a rich set of mathematical functions and operations that can be applied to entire arrays.

# 'contiguous/continuous memory allocation' is crucial for performance: it allows for efficient caching and vectorization of operations.
# Interview Point: Be able to articulate why NumPy is faster and more memory-efficient than Python lists for numerical data.

In [ ]:
import numpy as np # importing numpy

In [ ]:
# create a numpy array

my_arr = np.array([1,2,3,4,5,6])
my_arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
# We can take input of diff data types
# But it is stored in one(homogeneous data)
# Revision Point: NumPy arrays are homogeneous. If you try to mix data types, NumPy will implicitly upcast elements to the most general type possible (e.g., int to float, or any to string).
# This ensures all elements have the same data type for efficient operations.

In [ ]:
arr = np.array([1,2,3,4,"Helloe","fish",6.89,True])
arr

array(['1', '2', '3', '4', 'Helloe', 'fish', '6.89', 'True'], dtype='<U32')

In [ ]:
# Priority Order- String > float > boolean > integer
# Revision Point: When NumPy encounters mixed data types in an array, it follows a specific hierarchy for type promotion (upcasting).
# The array's `dtype` will be set to the type that can accommodate all other types without loss of information.

In [ ]:
arr1 = np.array([1,2,3,4,5.5])
arr1

array([1. , 2. , 3. , 4. , 5.5])

In [ ]:
arr2=np.array([1,2,3,4,True])
arr2

array([1, 2, 3, 4, 1])

In [ ]:
type(arr2)  # ndarray - NumPy's core object, representing n-dimensional arrays of homogeneous data.
# Revision Point: `ndarray` is the foundation of NumPy. It's a memory-efficient container that provides fast numerical operations.

numpy.ndarray

In [ ]:
# Dimensions - []

one_arr=np.array([1,2,3,4,5,6,7])

# 1-D array (Vector): An array that has 0-D arrays as its elements.
# Interview Point: Understand the concept of 'rank' or 'dimension' of an array. A 1D array is like a list of numbers.

In [ ]:
one_arr.ndim # `ndim` attribute returns the number of array dimensions (axes/rank).
# Revision Point: `ndim` is useful for quickly understanding the structure of your array.

1

In [ ]:
# 2-D array (Matrix): An array that has 1-D arrays as its elements.
# Interview Point: 2D arrays are commonly used to represent tables or images (grayscale).

In [ ]:
two_arr = np.array([[1,2,3]])
two_arr

array([[1, 2, 3]])

In [ ]:
two_arr.ndim

2

In [ ]:
two_arr1=np.array([[2,3,4,5],
                  [5,6,7,8]])
two_arr1

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [ ]:
# 3-D array (Tensor): An array that has 2-D arrays as its elements.
# Interview Point: 3D arrays are often used in deep learning for representing color images (height, width, color channels) or video data.

In [ ]:
three_arr.ndim

3

In [ ]:
# Indexing
# NumPy array indexing works similarly to Python list indexing but extends to multiple dimensions.
# Access elements using square brackets `[]` and comma-separated indices for each dimension.

# 1-D array

In [ ]:
print(arr)

[10 20 30 40]


In [ ]:
print(arr[3])

40


In [ ]:
three_arr1 = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[11,12,13,14],[16,17,18,19]],
    [[21,22,23,24],[26,27,28,29]]

])
three_arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 12, 13, 14],
        [16, 17, 18, 19]],

       [[21, 22, 23, 24],
        [26, 27, 28, 29]]])

In [ ]:
three_arr1.ndim

3

In [ ]:
three_arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 12, 13, 14],
        [16, 17, 18, 19]],

       [[21, 22, 23, 24],
        [26, 27, 28, 29]]])

In [ ]:
# Target - 27
# For a 3D array (axis0, axis1, axis2), `three_arr1[idx0, idx1, idx2]` accesses a specific element.
# `three_arr1[2, 1, 3]` means: go to the 3rd 2D array (index 2), then the 2nd 1D array within it (index 1), then the 4th element in that 1D array (index 3).
print(three_arr1[2,1,3])

29


In [ ]:
# Slicing
# NumPy array slicing allows you to extract sub-arrays (views) of an array.
# Syntax: `[start:stop:step]` for each dimension. Omitting `start` defaults to 0, omitting `stop` defaults to end, omitting `step` defaults to 1.
# Revision Point: Slicing in NumPy returns a *view* of the original array, not a copy. Modifying the slice will modify the original array.
# Interview Point: Be aware of the difference between a view and a copy when slicing NumPy arrays. Use `.copy()` if you need an independent copy.

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr[2:5]

array([3, 4, 5])

In [ ]:
# 2-D

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr.shape # `shape` attribute returns a tuple indicating the size of the array in each dimension (rows, columns, etc.).
# Revision Point: `shape` is crucial for understanding the layout of your data and debugging dimension-related errors.

(2, 5)

In [ ]:
arr[0,2:]

array([3, 4, 5])

In [ ]:
arr[1,1:]

array([ 7,  8,  9, 10])

In [ ]:
#3-D array

In [ ]:
arr1=np.array([[[1,2,3,4,5],[6,7,8,9,10]],
               [[11,12,13,14,15],[16,17,18,19,20]],
               [[21,22,23,24,25],[26,27,28,29,30]]
               ])
arr1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [ ]:
arr1.ndim

3

In [ ]:
arr1[0,1,0:2]

array([6, 7])

In [ ]:
# Reshape
# The `reshape()` method allows you to change the shape of an array without changing its data.
# Constraint: The total number of elements in the array must remain the same before and after reshaping.
# Revision Point: `reshape` is very common in data preparation, especially for feeding data into machine learning models that expect specific input shapes (e.g., 2D for feature matrices, 3D for image data).
# You can use `-1` as one of the dimensions in `reshape` to automatically calculate its size.

In [ ]:
arr = np.array([[1,2,3,4,5],[2,6,8,9,5]])

In [ ]:
arr.shape

(2, 5)

In [ ]:
arr.reshape(1,10)

array([[1, 2, 3, 4, 5, 2, 6, 8, 9, 5]])

In [ ]:
arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [6, 8],
       [9, 5]])

In [ ]:
# Methods to create arrays
# np.zeros(shape, dtype=float): Creates an array filled with zeros.
# np.ones(shape, dtype=float): Creates an array filled with ones.
# np.full(shape, fill_value, dtype=None): Creates an array of the given shape and fills it with `fill_value`.
# np.identity(n, dtype=float): Creates a square identity matrix (2D array where the main diagonal is ones, and all other elements are zeros).
# np.eye(N, M=None, k=0, dtype=float): Creates a 2-D array with ones on the diagonal and zeros elsewhere, similar to `identity` but more flexible.
# Revision Point: These creation functions are essential for initializing arrays, often as placeholders or for specific mathematical operations.

In [ ]:
# Methods
# Example usage of array creation methods:

# np.zeros
zero_array = np.zeros((2, 3), dtype="int")
print(f"Zeros Array:\n{zero_array}")

# np.ones
one_array = np.ones((3, 2), dtype="int")
print(f"\nOnes Array:\n{one_array}")

# np.full
full_array = np.full((2, 2), 7)
print(f"\nFull Array (with 7s):\n{full_array}")

# np.identity
identity_matrix = np.identity(4, dtype="int")
print(f"\nIdentity Matrix (4x4):\n{identity_matrix}")

# np.eye (with offset diagonal)
eye_matrix = np.eye(3, 4, k=1) # 3 rows, 4 columns, diagonal shifted by 1
print(f"\nEye Matrix (3x4, k=1):\n{eye_matrix}")

# Revision Point: Practice using these methods to quickly generate arrays of desired shapes and initial values. This is common in simulations and numerical analysis.

Zeros Array:
[[0 0 0]
 [0 0 0]]

Ones Array:
[[1 1]
 [1 1]
 [1 1]]

Full Array (with 7s):
[[7 7]
 [7 7]]

Identity Matrix (4x4):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Eye Matrix (3x4, k=1):
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#  Random Values and Functions in NumPy
#
#  NumPy's `random` module is extensively used for generating arrays of random numbers, which is crucial for simulations, statistical modeling, machine learning (e.g., initializing weights), and more. It provides functions to generate random numbers from various distributions.

In [ ]:
x=np.random.randint(1,101) # `np.random.randint(low, high, size=None, dtype='l')` generates random integers from `low` (inclusive) to `high` (exclusive).
# Here, it generates a single random integer between 1 and 100 (inclusive).
x

# Revision Point: Understand the difference between `randint` (discrete uniform) and `rand` or `randn` (continuous uniform/normal distributions).
# Interview Point: Be able to explain the parameters of `randint` and give examples of when you would use random number generation (e.g., Monte Carlo simulations, train-test split, initial model weights).

78

In [ ]:
arr = np.random.randint(1,101,size=(2,3))
arr

array([[10, 51, 31],
       [ 5,  8, 53]])

In [ ]:
arr = np.random.randint(1,101,size=10)
arr

array([54,  6,  2, 93, 46, 65, 54, 17, 61,  8])

In [ ]:
ar = np.random.random((2,3)) # generates random values btw 0 and 1
ar

array([[0.36883794, 0.31510185, 0.03422458],
       [0.36808308, 0.60647055, 0.23799191]])

In [ ]:
# arange
# `np.arange([start,] stop[, step,], dtype=None)` creates an array with evenly spaced values within a given interval.
# It's similar to Python's built-in `range()` function but returns a NumPy `ndarray`.

x = np.arange(0,20) # n-1 is still applicable: Creates an array from 0 up to (but not including) 20 with a step of 1.
x

# Revision Point: `np.arange` is often used to generate sequences of numbers for array indexing, creating time series data, or as a basis for other mathematical operations.
# Interview Point: Be able to compare `np.arange` with `np.linspace` – `arange` uses a step value, while `linspace` uses a number of samples over a specified interval.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# Linspace
# `np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)` generates an array with a specified number of evenly spaced samples, calculated over the interval [start, stop].
# Unlike `arange`, `linspace` specifies the *number* of elements, not the step size.

x = np.linspace(0,6, num=5) # Generates 5 evenly spaced numbers between 0 and 6 (inclusive).
x

# Revision Point: `np.linspace` is very useful when you need a precise number of points between two values, such as for plotting functions or creating feature ranges.
# Interview Point: Clearly distinguish `linspace` from `arange`. `linspace` includes the `stop` value by default, whereas `arange` does not. Also, know how `num` and `endpoint` parameters affect the output.

array([0. , 1.5, 3. , 4.5, 6. ])

HANDSON (Practise Questions)

Que 1-- Create a numpy array from numpy array module with a data type float and integer

In [ ]:
arr_numpy = np.array([1.2,2.3,3.6,4.8,5.0,],dtype="float")
print(arr_numpy)
arr_numpy.dtype

[1.2 2.3 3.6 4.8 5. ]


dtype('float64')

In [ ]:
arr_int = np.array([87,88,22,34,23], dtype="int")
print(arr_int)
arr_int.dtype

[87 88 22 34 23]


dtype('int64')

Que 2--Create a numpy arrays that have zero, one, two, three dimensions. Also print the shape and dimensions created.

In [ ]:
arr_zero = np.array(12)
print(arr_zero)
print(arr_zero.ndim)
print(arr_zero.shape)

12
0
()


In [ ]:
arr_one = np.array([12,24,48,60,72])
print(arr_one)
print(arr_one.ndim)
print(arr_one.shape)

[12 24 48 60 72]
1
(5,)


In [ ]:
arr_two = np.array([[12,24,48,60,72],
                   [84,96,108,120,132]])
print(arr_two)
print(arr_two.ndim)
print(arr_two.shape)

[[ 12  24  48  60  72]
 [ 84  96 108 120 132]]
2
(2, 5)


In [ ]:
arr_three = np.array([[[12,24,48,60,72],[84,96,108,120,132]],
                      [[11,22,33,44,55],[66,77,88,99,110]],
                      [[13,26,39,52,65],[78,91,104,117,130]]])
print(arr_three)
print(f'\n dimension of the given 3-D array is {arr_three.ndim}')
print(f'\n shape of the given array is {arr_three.shape}')

[[[ 12  24  48  60  72]
  [ 84  96 108 120 132]]

 [[ 11  22  33  44  55]
  [ 66  77  88  99 110]]

 [[ 13  26  39  52  65]
  [ 78  91 104 117 130]]]

 dimension of the given 3-D array is 3

 shape of the given array is (3, 2, 5)


Que - 3 Calculate the numpy array in the shape 2X3 with random integers in the range 0-100. Reshape the array in the shape 3X2 an print the updated shape of the resultant array.


In [ ]:
import numpy as np
arr_2 = np.random.randint(0,100, size=(2,3))
print(arr_2)
print(f'\nShape of arr_2 is {arr_2.shape}')

[[27 26 43]
 [95 72  1]]

Shape of arr_2 is (2, 3)


In [ ]:
arr=arr_2.reshape(3,2)

In [ ]:
print(arr)

[[27 26]
 [43 95]
 [72  1]]


In [ ]:
print(arr.shape)

(3, 2)


Que-4 Create a numpy rray that has a shape of 3*5 an all elements should be 5.


In [ ]:
arr_five = np.full((3,5),5)
print(arr_five)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Que-5 Create a array with random integer values between o-1000 with a size of 50 elements and perform operations:-
a) Print the first ten elements of the array
b) Print the last ten elements of the array.
c) Print the element from theindex 10-25.
d) print the element present at index 22.
e) Print the last ten elements of the array using negative indexing.

In [ ]:
arr_ran = np.random.randint(0,1000,size=50)
print(arr_ran)

[159 473 126 971 920 164 757 140  27  73 507 274 982 399 586 954 491 935
 795 672 598 854 640 978 807 913 569 674 628 674  18 414 582 715 889 183
 197 600 390 342 325 518 815 808 281   5 152 959 350 196]


In [ ]:
print(arr_ran[0:10])

[159 473 126 971 920 164 757 140  27  73]


In [ ]:
print(arr_ran[40:])

[325 518 815 808 281   5 152 959 350 196]


In [ ]:
print(arr_ran[10:26])

[507 274 982 399 586 954 491 935 795 672 598 854 640 978 807 913]


In [ ]:
print(arr_ran[22])

640


In [ ]:
print(arr_ran[-10:])

[325 518 815 808 281   5 152 959 350 196]


Que-6 Given a Numpy array that has the values=[1,2,3,4,5]. Perform the following operations:-
a) Insert the elemnt 6 at the end of the array.
b) Insertthe element 10 at the beginning of the array.
c) Insert the elemnt 30 before 4.
d) Delete the element 30.

In [ ]:
num_arr = np.array([1,2,3,4,5])
print(num_arr)

[1 2 3 4 5]


In [ ]:
#a
np.append(num_arr,6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#b
num_arr = np.insert(num_arr,0,10)
print(num_arr)


[10  1  2  3  4  5]


In [ ]:
#c
num_arr = np.insert(num_arr,4,30)
print(num_arr)


[10  1  2  3 30  4  5]


In [ ]:
np.delete(num_arr,4)

array([10,  1,  2,  3,  4,  5])